### ISSUE TITLE
Module object not callable

### ISSUE THREAD

**Issue by gurchk** [ICSec/airpwn-ng#21]
Traceback (most recent call last):
  File "./airpwn-ng", line 225, in <module>
    main(args)
  File "./airpwn-ng", line 118, in main
    style.handler(args, websites)
  File "/root/Desktop/airpwn/airpwn-ng/lib/styles.py", line 63, in handler
    snif.threaded_sniff(args)
  File "/root/Desktop/airpwn/airpwn-ng/lib/sniffer.py", line 68, in threaded_sniff
    q = Queue()
TypeError: 'module' object is not callable

**Comment by stryngs** [comment]
Hi Gurchk,

I just ran:
git clone https://github.com/ICSec/airpwn-ng
cd airpwn-ng
./airpwn-ng

Everything ran just fine.  Can I get more an idea of exactly what you did?  I know that doesn't exactly help right away, but seems like a strange bug, stopping on q = Queue()

**Comment by gurchk** [comment]
Thanks for your response, i figured it out, i had to change it to q = Queue.Queue()

Den 16 apr. 2017 3:56 em skrev stryngs <notifications@github.com>:

Hi Gurchk,

I just ran:
git clone https://github.com/ICSec/airpwn-ng
cd airpwn-ng
./airpwn-ng

Everything ran just fine. Can I get more an idea of exactly what you did? I know that doesn't exactly help right away, but seems like a strange bug, stopping on q = Queue()

**Comment by stryngs** [comment]
Which version of Python are you running this with?

**Comment by stryngs** [comment]
Very strange, I'm using 2.7.12 and I don't suffer that module issue.  Queue is in the namespace as:
from Queue import Queue
q = Queue.Queue() shouldn't be needed, nor should it work...

This is a head scratcher.

**Comment by gurchk** [comment]
Yes i have no idea why either... I am also having troubles getting it to actually work. This is what i have done:
1. Put my NIC in monitor mode    -    airmon-ng start wlan1 6
2. Start up dot11decrypt              -     ./dot11decrypt wlan1mon wep:BSSID:PASS
3. Start up Airpwn                        -    ./airpwn-ng -m tap0 -i wlan0 --inject payloads/wargames
4. Browse to www.foo.com on my phone on the network
5. Nothing happends..

Would be happy if you could help me out.

**Comment by Jack64** [comment]
@gurchk You missed the step where you deauth your phone in order for dot11decrypt to capture the EAPOL handshake between the WiFi router and your phone, so that it can see the GET request for foo.com ;) aireplay-ng should do the trick.

**Comment by stryngs** [comment]
@gurchk 
./dot11decrypt wlan1mon wep:BSSID:PASS
./airpwn-ng -m tap0 -i wlan0 --inject payloads/wargames

Those steps are correct for attacking WEP.  Dot11Decrypt can be buggy at times (pyDot11 is almost complete...), so first step is to make sure it is passing info to tap0.  Get Dot11Decrypt up and running, and then tcpdump or ngrep on tap0.  Once you've verified you see traffic on tap0, then you're ready to use it as -m for airpwn-ng.

Another thing to be known is that ideal sniffing is > 10ft away.  Anything closer than 10ft can have unexpected consequences from the physics side of the house.

Lastly, both Jack64 and I are on IRC.  Sometimes that can be a better method of figuring out things.  If you get a chance, drop by irc.freeenode.net and check out ##ha.

**Comment by gurchk** [comment]
@stryngs 
Thanks for making things a bit more clear ! I'm gonna try this out right now. Do you mean 10ft from the actual router or from the client (phone)? I will definitely connect to IRC if i have any more issues. Thanks again.

@Jack64 
Thanks for your quick answer, but I thought you did not need the handshake on a WEP Encrypted network. Maybe i might be off here..

**Comment by Jack64** [comment]
@gurchk totally missed the fact you were using attacking WEP, I always test against WPA so that was my bad. It should be working, so make sure you're on the correct channel (only thing that occurs to me that could be mismatched) with airodump-ng -c <chan> .
Definitely drop by ##ha on IRC if you need more help.

**Comment by stryngs** [comment]
@gurchk,
You are on to something.  Have started implementing specific versions of scapy as it turns out the .debs are diff from the pips and from the gits...  Thus, currently settled on scapy2.3.3 from pypi.  Would like to know which version of scapy you have?

**Comment by stryngs** [comment]
@gurchk,
Grab the newest commit.  pip install scapy.  Play with airpwn-ng and please let me know if it works as expected.  Of note, I recommend testing on Open Environment first.  Once you see it works for open wifi, then move to playing with encryption (dot11decrypt has issues sometimes)

**Comment by gurchk** [comment]
@stryngs 
Tried running pip install scapy 
`[gpole@gpole ~]$ pip install scapy
Collecting scapy
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-518l7b_k/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token`
I know this is fixable by just removing the 0 in 0755 but where do i find the cached scapy-2.3.3.

**Comment by stryngs** [comment]
Make sure you are in the airpwn-ng directory
wget https://pypi.python.org/packages/ac/14/c792a14b9f8bc4bb9c74c0594c167a2da36e31964098d9e27202142cbd7d/scapy-2.3.3.tgz
tar zxf scapy-2.3.3.tgz
mv scapy-2.3.3/scapy .
rm -rf scapy-2.3.3

Now you should have it

**Comment by stryngs** [comment]
@gurchk,
Forgot to mention, so Once you've detar'd and moved the folder, airpwn-ng will now call the modules in the folder instead of requiring them on the machine.  If they're already on the machine, then because the folder is local, it'll be ran instead.  Simply having airpwn-ng/scapy is enough to make this work for you.

Also, make sure you grab the latest public commit for airpwn-ng, it's moded to work with scapy2.3.3.

**Comment by gurchk** [comment]
@stryngs 
Alright ! Just grabbed the latest commit of Airpwn but i get pydot11 error although i have pydot11 in a dir in airpwn-ng/

`[gpole@gpole airpwn-ng]$ ls
airpwn-ng  archives  DEBs  INFOs  lib  payloads  pyDot11  README.md  RESOURCEs  scapy  work-in-progress
[gpole@gpole airpwn-ng]$ ./airpwn-ng 
    from pyDot11 import *
ImportError: No module named pyDot11
`

**Comment by stryngs** [comment]
@gurchk 
Hang tight.  Do you have a moment to where you can get on IRC?
pyDot11 != airpwn-ng =)

**Comment by gurchk** [comment]
@stryngs 
Already on ;) nick gurchk or gpole

**Comment by stryngs** [comment]
irc.freenode.net?

**Comment by stryngs** [comment]
@gurchk,
Thanks for the input, glad we got a workaround done, and i'll make those mods for situations like yours.
