### ISSUE TITLE
Replace Image

### ISSUE THREAD

**Issue by akballow** [ICSec/airpwn-ng#9]
Hi I love what you done with getting airpwn to much easier to get working.
I see that we are able to inject html, but how do I like in airpwn replace images, for example to replace all .jpegs on a site with my target? 

Greatly appricate a response :)

**Comment by stryngs** [comment]
Happy to hear someone is using it =)

I've been out all night so I'm not in a condition to try and explain stuff now.  Expect a response from Jack64 or myself sometime within the next 24 hours.  Jack64 is probably your best option honestly; he is responsible for the python implementation; I'm just the bash guy =)

Thank you for feedback!

**Comment by stryngs** [comment]
akballow,

Do you use IRC?  It might be a little easier to explain what is going on that way.

**Comment by Jack64** [comment]
Hey there @akballow ,

Sorry for the slow response, I've been a bit busy lately.
The best way to achieve that would be to inject javascript that performs whatever changes you need on the page, but it requires using the API and it's still work in progress. The main goal of airpwn-ng is to force the victim to make requests to other websites using stored cookies so you can grab them and highjack a session, so I focused on that during development.

**Comment by stryngs** [comment]
@akballow Have you played with the tool lately?  Vastly improved from the bash days.
